DROP DATABASE IF EXISTS joshterrell_com;
CREATE DATABASE joshterrell_com;
USE joshterrell_com;

CREATE TABLE users (
  idx INT UNSIGNED NOT NULL AUTO_INCREMENT,
  id VARCHAR(255) NOT NULL UNIQUE,
  PRIMARY KEY (idx)
);

INSERT INTO users (id) VALUES ('joshterrell805@gmail.com');

CREATE TABLE sessions (
  user_idx INT UNSIGNED NOT NULL foregin
);

CREATE TABLE docs (
  idx INT UNSIGNED NOT NULL AUTO_INCREMENT,
  publish_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  edit_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  title VARCHAR(255) NOT NULL UNIQUE,
  body TEXT NOT NULL,
  doctype ENUM('article', 'post') NOT NULL,
  private BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (idx)
);
